CREATE TABLE user (
  id VARCHAR(36) PRIMARY KEY,
  sku_id VARCHAR(255) NOT NULL,
  cpf VARCHAR(20) NOT NULL,
  name VARCHAR(50) NOT NULL,
  address VARCHAR(200) NOT NULL,
  email VARCHAR(100) NOT NULL,
  
  UNIQUE (cpf)
)

